version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - mynetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - mynetwork